### ISSUE TITLE
XAMARIN FORMS - WS SOAP

### ISSUE THREAD

**Issue by ejastre** [willbuildapps/xamarin-duvidas#1]
É possível consumir um WebService SOAP da PCL? Ou somente mesmo adicionando a WebReference nos projetos Android/iOS?

**Comment by wsrzx** [comment]
Olá tudo bem @ejastre, você vai encontrar na internet N explicações dizendo que é possível, se usar um profile PCL especifico, etc... 

Porem a forma recomenda está descrita [aqui](https://developer.xamarin.com/guides/xamarin-forms/cloud-services/consuming/asmx/). 

Espero ter te ajudado. 🙂
