### ISSUE TITLE
App Store rejeitando aplicativo alegando problemas no IPV6 na Wifi

### ISSUE THREAD

**Issue by elyfran** [willbuildapps/xamarin-duvidas#10]
Galera, tudo bem.

Algum de vocês já passaram pelo problema na revisão do aplicativo na app store, pois esta sendo rejeitado pro problema de ipv6 na wifi. No emulador e iphone funciona perfeitamente.

Vocês teriam alguma dica ou algo do tipo para solucionar essa questão?

**Comment by ionixjunior** [comment]
Olá @elyfran, na sua programação como você insere o endereço de sua API? Através de um endereço IP ou usa domínio?

Sempre utilizo domínio e não encontro este problema.

**Comment by wsrzx** [comment]
@elyfran, eu não sei qual o retorno que você teve da Apple, mas você pode tentar as seguintes soluções:

- [Possíveis problemas e soluções](https://blog.xamarin.com/making-your-ios-apps-ipv6-ready/)
- [Como você pode testar](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW16)

Abraço.

**Comment by elyfran** [comment]
@ionixjunior e @willbuildapps obrigado pelo retorno e desculpe a demora em responder.

@ionixjunior 
eu uso sempre o dominio utilizando httpclient.

@willbuildapps 
Amigo, os tópicos enviados já verifiquei anteriormente. Sobre o artigo do James utilizo o httpclient e continua dando o mesmo problema. Já criei uma rede wifi NAT64 em um mac e funciona normalmente o app no iphone, mas quando submete para appstore sempre rejeita.

Motivo da rejeição é de problema de conectividade utilizando IPV6 na wifi. (somente na WIFI)

**Comment by wsrzx** [comment]
Ence

**Comment by wsrzx** [comment]
@elyfran você está usando qual handler nativo para http em seu App?  Como são  feitas duas chamadas para os endpoints? Esses endpoitns são seguros (https)?

Você pode postar aqui a mensagem de refeição da Apple? 

Abraço.

**Comment by elyfran** [comment]
@willbuildapps , boa tarde, tudo bem? obrigado novamente pelo apoio.

Hoje utilizo HTTP mas antes utilizava HTTPS, porém ambos foram rejeitados.

Conforme solicitado segue abaixo uma amostra do processo de login:


private const string apiUrl = "https://API";

		static HttpClient CreateClient()
		{
			return new HttpClient(new ModernHttpClient.NativeMessageHandler());
   		}

		public static async Task<UsuarioER> RealizarLogin(string login, string senha)
		{			
			try
			{
				var formContent = new FormUrlEncodedContent(new[]
				{
					new KeyValuePair<string, string>("grant_type", "password"),
					new KeyValuePair<string, string>("username", login),
					new KeyValuePair<string, string>("password", senha)
				});

				using (var client = CreateClient())
				{
					if (client.DefaultRequestHeaders.CacheControl == null)
					client.DefaultRequestHeaders.CacheControl = new CacheControlHeaderValue();

					client.DefaultRequestHeaders.CacheControl.NoCache = true;
                    client.DefaultRequestHeaders.IfModifiedSince = DateTime.UtcNow;
                    client.DefaultRequestHeaders.CacheControl.NoStore = true;
                    client.Timeout = new TimeSpan(0, 0, 30);

					client.BaseAddress = new Uri(apiUrl);
					client.DefaultRequestHeaders.Add("Accept", "application/json");

					var response = await client.PostAsync("/Login", formContent);
						
						var content = await response.Content.ReadAsStringAsync();

						UsuarioER usuario = JsonConvert.DeserializeObject<UsuarioER>(content);

						Settings.AccessToken = JsonConvert.SerializeObject(usuario);

						return usuario;
				}
			}
			catch (Exception ex)
			{
				Xamarin.Insights.Report(ex);
				return null;
			}
		}

**Comment by elyfran** [comment]
Segue a mensagem enviada da revisão:

Guideline 2.1 - Performance

Thank you for your resubmission.
Your app crashed on iPhone running iOS 10.3.1 connected to an IPv6 network when we:
Attempt to sign in with the provided demo account.
This occurred when your app was used: On Wi-Fi

**Comment by wsrzx** [comment]
@elyfran, desculpe a demora eu simulei tudo que vocês e comparei com outros 5 aplicativos que tenho publicado na App Store, o primeiro deles reprovado pelo mesmo problema e as solução apontadas nesta issue, resolvem o problema.

Por isso estou fechando a issue, caso alguém ou você encontre uma solução que não esta listada aqui, pode reabrir e incluir para consultas futuras.

Abraço.
