### ISSUE TITLE
Aprendendo a Desenvolver em Xamarin

### ISSUE THREAD

**Issue by SulivanSouzaDev** [willbuildapps/xamarin-duvidas#11]
Olá William me chamo Sulivan minha formação e Design Gráfico mas tenho algum conhecimento em PHP e faço ja alguns trabalhos na web utilizando Wordpress, mas gostaria de me aprofundar mais em desenvolvimento e gostei e proposta Xamarin e tenho interesse em desenvolver aplicativos para mobile. 
Seria possível me orientar aonde busco mais informações de como inicio um aprendizado para desenvolver utilizando a tecnologia Xamarin? 

Fico grato se puder ajudar

abs
Sulivan

**Comment by alexsandre** [comment]
Sulivan,

A página de documentação do Xamarin é bem útil para aprendizado e além dela existe a Xamarin University com bons conteúdos também. Apesar de pago a Xamarin University possui um período trial que pode ajudar na decisão de assinar ou não o serviço deles.

Além disso existe o blog da Xamarin: [https://blog.xamarin.com](https://blog.xamarin.com). E por coincidência, há poucos dias saiu um post muito bom com dicas para superar a curva de aprendizado. O post é esse: [https://blog.xamarin.com/xamarin-forms-tips-beating-learning-curve/](https://blog.xamarin.com/xamarin-forms-tips-beating-learning-curve/)

Link para página de documentação/guides do Xamarin: [https://developer.xamarin.com/guides/](https://developer.xamarin.com/guides/)

E além disso tudo existe as iniciativas do pessoal aqui do Brasil, como o William e outros. Postagens em blogs, eventos são frequentes e bem úteis.

Acho que pode iniciar pela documentação e em caso de dúvidas específicas recorrer a ajuda da galera, como esse próprio github.

Abs!

**Comment by wsrzx** [comment]
@SulivanSouzaDev tudo bem cara?

Seguinte eu vou discordar um pouco do @alexsandre, pois penso que existe uma forma mais simples de iniciar do zero do que ler apenas a documentação, isso pode ser extremamente maçante para quem está começando e não conheçe ou conhece muito pouco da tecnologia que é objeto do seu estudo, sem falar que é desestimulante também.

O que eu recomendo é começar por entender é entender o contexto do problema que o Xamarin se propõe a resolver, depois entender o que é Xamarin e o que é Xamarin.Forms,  vou listar algumas playlist com videos (alguns longos) que podem te ajudar.

Superando a curva "do que é", ai você pode começar com a curva do "como faz", e ai a documentação vai te ajudar muito.

Mas e a Xamarin University? É bom, é caro, o trial ajuda, mas quando alguém indica a XU, vale sempre deixar claro que o conteúdo lá é em inglês e por muitas vezes isso adiciona mais um grau de dificuldade na curva de aprendizado. 

### Vamos lá:

**Intensivão de Xamarin parte 1 – O que é Xamarin?** 
https://www.youtube.com/watch?v=OVqg8AjpeMQ

**Intensivão de Xamarin parte 2 – Como funciona o desenvolvimento multiplataforma iOS, Android e UWP?** 
https://www.youtube.com/watch?v=fW8rY0gBA3s

**Intensivão de Xamarin parte 3 – O que é Xamarin Forms?** 
https://www.youtube.com/watch?v=N6PjLE18thE

**Intensivão de Xamarin parte 4 – Preparando o ambiente de desenvolvimento** 
https://www.youtube.com/watch?v=TKBnt6fxz5Y

**Intensivão de Xamarin parte 5 – Integrando serviços de back-end na nuvem com seu app**
https://www.youtube.com/watch?v=qohwWMmn9AI

**Intensivão de Xamarin - Demo parte 1** 
https://www.youtube.com/watch?v=6oZCg1EWFzA

**Intensivão de Xamarin - Demo parte 2** 
https://www.youtube.com/watch?v=cMoXaJneTfg

**Intensivão de Xamarin - Demo parte 3** 
https://www.youtube.com/watch?v=xSfxzx9nRPs 

**Intensivão de Xamarin - Demo parte 4** 
https://www.youtube.com/watch?v=_gB1q0agjaI

**Intensivão de Xamarin - Demo parte 5** 
https://www.youtube.com/watch?v=WjbJ1ldTvjM

**Desenvolvimento com Xamarin Dúvidas Gerais:** https://www.youtube.com/channel/UCFaQBRaoHrAxcGoeY8E5jvQ/playlists 

Forte Abraço
