### ISSUE TITLE
Contas de usuário

### ISSUE THREAD

**Issue by perez-danilo** [willbuildapps/xamarin-duvidas#12]
Will, boa tarde,

meu App e meu WebApi precisarão ter autenticação usando facebook, google ou criação de conta padrão via email e senha.
Estou usando Xamarin forms.
Como você faria essa solução?

Obrigado

**Comment by wsrzx** [comment]
Opa, se liga o Angelo tem um video falando disso https://www.youtube.com/watch?v=cyq_ho4QflQ&feature=youtu.be
