### ISSUE TITLE
OpenGL - Disney Experience

### ISSUE THREAD

**Issue by luisfernandomoraes** [willbuildapps/xamarin-duvidas#17]
É possivel criar um app similar ao https://play.google.com/store/apps/details?id=com.disney.mdx.wdw.google usando xamarin e OpenGL?

**Comment by wsrzx** [comment]
Opa @luisfernandomoraes é possível criar, (eu só não afirmo que o app em questão usa OpenGL), eu no seu lugar pesquisaria um pouco mais para entender a arquitetura deste aplicativo antes de desenvolver um similar.

Abraço.
