### ISSUE TITLE
Problema de Memória com XF

### ISSUE THREAD

**Issue by NelsonSantos** [willbuildapps/xamarin-duvidas#18]
Fala pessoal...

Estamos desenvolvendo um produto que irá ser usado para vendas internas de dentro de um estabelecimento (lojas, mercados, etc).

Nosso layout (o que chamamos de vitrine) conta com uma listview em colunas (FlowListView) onde temos uma imagem, a descrição o preço do produto, além de algumas outras pequenas informações e um botão "Comprar".

As imagens utilizadas na vitrine estão no dispositivo, baixadas por um processo a parte.

Fizemos várias melhorias em design usando Grid Control, evitando StackLayouts aninhados para otimizar memória. Usamos também o controle CachedImage para melhoria das imagens, etc.

"Ligamos" o Fast Renderer, porém ainda não implementamos o "Layout Compression".

Para o desenvolvimento usamos Xamarin Forms, sem nenhum outro framework (Prism, MVVMLight, MVVMCross, etc), porém estamos usando o padrão MVVM.

O sistema é todo on-line com acesso a dados via WEB-API com Flurl. Em nossa vitrine o JSON que a compõe, retorna os dados do produto é bem carregado de informações (cada produto tem uma ou mais váriações/skus, opções de cores e ou tamanhos, etc), porém no momento é bem limitado a no máximo uns 30 itens, que uma vez "baixado" na vitrine segue todo o ciclo da venda até o seu final quando é carregado novamente.

Porém nosso problema é que feitos algumas vendas (existe todo um processo/ciclo para isso) o aplicativo cai por problema de memória.

Eu creio que nosso problema não é layout pesado, pois até onde eu consegui investigar, notei que a cada ciclo de venda a memória usada no aplicativo vai aumentando, até chegar no limite do dispositivo e ocorrer o estouro de memória.

Minha dúvida é o seguinte, em relação a qual caminho tomar:

1) Se implementar uma interface IDisposable em cada classe/model definindo os objetos utilizados em null ajudaria no problema?

2) Usar algum esquema de Singleton?

3) Reescrever boa parte do código usando algum dos frameworks citados acima?

Agradeço a quem puder me ajudar.

Abraços...

Nelson Santos

**Comment by wsrzx** [comment]
Já tentou rodar um profiler?
