### ISSUE TITLE
.NET Standard com Visual Studio for Mac 2017 (v7.x)

### ISSUE THREAD

**Issue by dddanielsc** [willbuildapps/xamarin-duvidas#19]
Boa tarde ! 

Há um tempo comecei Xamarin, iniciei pelos vídeos do que há no youtube da Microsoft, depois fui pra documentação sempre usando a estratégia de PCL. Entretanto percebi algumas limitações em relação com alguns pacotes nugets (exemplo: [Microcharts](https://github.com/aloisdeniel/Microcharts) , que eu uso muito gráfico). Percebi que ele (o microcharts ) usa o .Net Standard 1.4. Comecei a pesquisar sobre encontrei alguns posts [mostrando como migrar](https://channel9.msdn.com/Shows/XamarinShow/Snack-Pack-15-Upgrading-to-XamarinForms-to-NET-Standard?ocid=player)  (tem esse [aqui](https://xamarinhelp.com/upgrade-pcl-net-standard-class-library/) tbm),  mas sempre há um problema, não consigo buildar o projeto, há duplicações de arquivos e etc ...  Pra facilitar o desenvolvimento seria muito interessante o uso do .Net Standard. Procurei no Monkey Hub e não achei nada que fosse dessa alçada. Hoje uso o Visual Studio Community for Mac , não sei se há alguma [diferença](https://developer.xamarin.com/guides/xamarin-forms/under-the-hood/net-standard/). Se vc puder me ajudar como montar um projeto usando .NET Standard (de preferência o 2.0)+ Xamarin.Android + Xamarin.iOS, ficaria muito grato.

**Comment by wsrzx** [comment]
Olá @dddanielsc neste repo aqui tem um projeto de referencia (basico) feito com .net standard 2.0 https://github.com/willbuildapps/learn-xamarin-forms/tree/demos/popular_games_app 

Se não te ajudar me avisa. Abraço.
