### ISSUE TITLE
WebView auto login

### ISSUE THREAD

**Issue by sanugav1** [willbuildapps/xamarin-duvidas#2]
É possível fazer um login automático usando o componente webview do xaml? Fiz algumas pesquisas e não encontrei solução ainda. 

P.S. Sou novo em Xamarin.

**Comment by wsrzx** [comment]
Olá @sanugav1, vou tentar reponder a sua pergunta.

Supondo que você tenha um formulário de login esta página que vai abrir dentro da webview você poderia tentar algo como [chamar uma função javascript](https://developer.xamarin.com/recipes/cross-platform/xamarin-forms/controls/call-javascript/) para fazer autenticação e trabalhar com o retorno desta função.

Caso isso não tenha te ajudado, me explique melhor o que você precisa fazer. 🙂

Abraço.
