### ISSUE TITLE
Sqlite versões Nougat e Orio

### ISSUE THREAD

**Issue by winstondb** [willbuildapps/xamarin-duvidas#20]
Montei um app usando o sqlite e funciona muito bem no Android 6.0, porém, em versões superiores como o Nougat 7.0 e o Orio 8.0 ocorre um erro que é mostrado numa popup.

Detected problems with app native libraries(please consult log for details): libmonosgen-64bit-2.0.so: unauthorized access to "/system/lib64/libsqlite.so"

Há uma solução pra este problema?

**Comment by wsrzx** [comment]
Opa, da uma lida neste artigo aqui https://blog.xamarin.com/preparing-for-native-library-linking-changes-in-android-n/ ele explica muito do que é preciso fazer.
