### ISSUE TITLE
Polígonos em mapa

### ISSUE THREAD

**Issue by viniciusvelasco** [willbuildapps/xamarin-duvidas#3]
Olá,

Tenho um app (por restrição de contrato não posso mostrar) que utilizo desenhos de polígonos em mapas. Geralmente são desenhados entre 15 e 50 polígonos que conforme a informação possui uma determinada cor e quando toco nele chama uma nova tela para lançamento para aquele polígono/área. Isso de certa forma funciona mas tenho enfrentado alguns problemas, por exemplo: para saber o polígono que toquei preciso capturar a coordenada tocada e calcular dentro de qual polígono ela esta e isso gera uma lentidão.

**A dúvida é:**

É possível criar um tipo de evento que eu soubesse em qual polígono eu toquei sem precisa desse cálculo?
É possível utilizar MVVM na renderização dos polígonos?

**Comment by wsrzx** [comment]
Olá @viniciusvelasco, tudo bem? 

Eu vou tentar responde a sua pergunta baseado no que é possível se fazer focando em como eu faria, entendi que a sua dúvida é mais focado em algo especifico para necessidade do seu app do que uma dúvida relacionada ao Xamarin, vamos lá 🙂:

_Respondendo a primeira e segunda pergunta:_ Se você estiver usando Xamarin.Forms por exemplo (estou supondo),  dependendo da forma como você está desenhando esse polígono, seria possível adicionar um [Tap Gesture Gesture Recognizer](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/gestures/tap/) e fazer binding a um Command que teria como parâmetro o objeto selecionado referente a polígono tocado pelo usuário, dessa forma seria possível usar MVVM/eventos.

Caso eu não tenha ajudado na sua dúvida, me ajude com mais informações de como você está fazendo e o que está usando, que com isso eu posso tentar novamente 😀

Abraço.

**Comment by viniciusvelasco** [comment]
Obrigado. Vou tentar isso e digo como foi.

**Comment by wsrzx** [comment]
Vou fechar a issue, mas depois diz ai como ficou :)
