### ISSUE TITLE
Xamarin.Forms: clicar em um ponto do mapa e selecionar latitude e longitude

### ISSUE THREAD

**Issue by LeandroPereiras** [willbuildapps/xamarin-duvidas#4]
Estou utilizando o Xamarin.Forms.Maps conforme o recomendado pela documentação. Porém, preciso permitir que o usuário toque em um ponto do mapa e nesse momento devo capturar a latitude e longitude.

Atém onde descobri o Xamarin.Forms.Maps não possui essa funcionalidade, comecei a fazer com Custom renderer, o que vocês sugerem? Alguma Lib, custom renderer, xamarin effects, outra sugestão?

**Comment by wsrzx** [comment]
Olá tudo bem @LeandroPereiras a melhor forma de fazer isso é através de um custom renderer, em uma pesquisa rápida eu achei este projeto aqui, veja se te ajuda https://github.com/halkar/XamarinExtendedMap. 

Abraço 🙂
