### ISSUE TITLE
Gcm.Client

### ISSUE THREAD

**Issue by dayaneLima** [willbuildapps/xamarin-duvidas#5]
Uso a biblioteca Gcm.Client para pegar os registrationIds dos usuários do app, mas preciso saber de qual usuário é cada registrationId.
Assim obtenho esse id eu armazeno usando aquele plugin de settings, e quando o usuário se autentica, eu envio esse registrationId para o backend armazenar,  apontando que o registrationId é do usuário que se autenticou.
Mas se o usuário desinstalar o aplicativo, eu ainda fico com aquele registrationId gravado no banco de dados, tem como eu saber que o aplicativo está sendo desinstalado ou algo assim para remover esse registrationId da minha base de dados?

Eu necessitava saber se o usuário logou em outro dispositivo, para deslogar do atual, então eu me baseio nesse registrationId. Quando o usuário loga no app, eu vejo se o registrationId atual dele é diferente do anterior, se for, eu mando um push para esse antigo, informando que foi efetuado login em outro dispositivo. Eu precisava de uma espécie de identificador do dispositivo.
Pois testei desinstalar e instalar novamente o app no mesmo celular, e o mesmo recebeu o push que havia feito login em outro dispositivo, sendo que era o mesmo aparelho, os dois registrationId continuaram funcionando (o antigo e o que gerou com a nova instalação).

**Comment by jbravobr** [comment]
@dayaneLima O controle sobre o registro dos aparelhos em APN para envio de push notification, não possui acessos para o desenvolvedor, não de forma explícita como você está especificando no seu caso proposto. O controle de instalações e desinstalações de aplicativos nativos é algo bem sensível para as plataformas. Há casos de contorno para a plataforma Android, mas é muito mais restrito na plataforma iOS. Todas as APNs possuem controles próprios para "sanitizar" sua base quanto ao registro "ativo" ou não de dispositivos que outrora tenham se registrado em sua APN, algum dia.

Eu, pela experiência que tenho, acredito que a sua tarefa de manutenir o estado de instalação/desinstalação é algo um pouco "além" para o atual paradigma, com aplicativos nativos.

**Comment by wsrzx** [comment]
Ola @dayaneLima complementando o que o @jbravobr disse, minha sugestão é você utilizar serviços como https://onesignal.com/ ou https://azure.microsoft.com/pt-br/services/notification-hubs/ que permitem que você envie notificações push e consiga gerenciar usuários/tag/device ids.

Abraço.

**Comment by wsrzx** [comment]
@dayaneLima vou encerrar a issue, caso não tenhamos te ajudado, favor reabrir :)
