### ISSUE TITLE
Windows 7 para desenvolver com Xamarin

### ISSUE THREAD

**Issue by joaogamin** [willbuildapps/xamarin-duvidas#6]
Posso usar Windows 7 para desenvolver com Xamarin ou somente Windows 10? Se sim qual seriam possíveis limitações ?

**Comment by jbravobr** [comment]
@joaogamin, não vejo porque você teria limitações para o Windows 7. O aporte necessário está na utilização do Visual Studio, versão 2015 ou 2017 e disto as instalações por detrás do "módulo" Xamarin para o Visual Studio, que completam com SDKs da Xamarin e para windows dos SDKs para Android.

**Comment by joaogamin** [comment]
@jbravobr blz, tinha visto em algum lugar que precisava do windows 10 especificamente para alguma coisa  no xamarin .

**Comment by wsrzx** [comment]
Opa, @joaogamin você tem limitações caso queira utilizar UWP, os pontos são, o recomendado é windows 10, porem com a seguinte observação:

> The minimum operating system version is Windows 7. Xamarin.Forms Windows support requires Windows 8.1, and Xamarin.Forms UWP support requires Windows 10.


[Aqui tem tudo bem completo](https://developer.xamarin.com/guides/cross-platform/getting_started/requirements/#windows) 😉

Abraço.

**Comment by wsrzx** [comment]
@joaogamin vou encerrar a issue, caso não tenhamos te ajudado, favor reabrir :)
