### ISSUE TITLE
Xamarin forms  Estimote SDK

### ISSUE THREAD

**Issue by chagasbass** [willbuildapps/xamarin-duvidas#7]
Boa tarde. Estou trabalhando com beacons da marca estimote e eles disponibilizam um sdk somente para acesso no Xamarin Android ou IOS, No momento estou usando o Xamarin forms. Existe alguma possibilidade de efetuar uma implementação de ambas as plataformas usando esse SDK para Xamarin forms? Obrigado!!

**Comment by wsrzx** [comment]
Opa, tudo bem @chagasbass  você pode utilizar um DependencyService para resolver a implementação de cada plataforma em um único ponto para utilização.

Recomendo a leitura de [Understand how DependencyService works to access native platform features](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/dependency-service/introduction/)

Abraço.

**Comment by chagasbass** [comment]
Opa Obrigado @willbuildapps ! Vou tentar aqui!
