### ISSUE TITLE
Diferenças de classes

### ISSUE THREAD

**Issue by smarane** [willbuildapps/xamarin-duvidas#8]
Boa noite! Estou com dúvida para criar uma classe. No meu material de estudo foi selecionado Biblioteca de Classe(Portátil para IOS, Android e Windows) no VS 2015. Estou utilizando o Visual Studio 2017 e não tenho esta classe. Só encontrei a Biblioteca de Classe(Portátil Herdado). É a mesma coisa? Caso negativo como preceder? 

Obrigada, 
Silvia

**Comment by wsrzx** [comment]
@smarane, pelo que eu entendi você deve estar utilizando o VS em pt-br, sua dúvida deve estar relacionada a PCL vs Shared Project, eu recomendo este video [aqui](https://www.youtube.com/watch?v=pn0MKcrm4xE), para te ajudar nessas dúvidas.

**Comment by wsrzx** [comment]
@smarane, estou encerrando essa issue, por tempo de inatividade. Abraço.
