### ISSUE TITLE
Problemas com plugin de notificação local

### ISSUE THREAD

**Issue by chagasbass** [willbuildapps/xamarin-duvidas#9]
Olá boa tarde, Estou usando um plugin para notificações locais no Xamarin forms (Local Notifications Plugin for Xamarin and Windows edsnider/LocalNotificationsPlugin).Consigo enviar a notificação mas fora do aplicativo quando toco na mesma o app volta para a tela de splash , ou seja ele reinicia.Existe algum contorno pra isso ou outro plugin para ser usado?

**Comment by ionixjunior** [comment]
Olá @chagasbass. Isso que você quer implementar chama-se **deep link**. Até onde sei não existe um plugin que faça isso, é um trabalho um pouco braçal.

Basicamente, você teria que enviar alguns parâmetros na notificação e quando clicar nela, ler estes parâmetros e decidir para qual tela ir.

**Comment by wsrzx** [comment]
@chagasbass estou encerrando essa issue, por tempo de inatividade. Abraço.
